### ISSUE TITLE
should be probably aqi_pm10_0. 

### ISSUE THREAD

**Issue by misko903** [jonathankoren/weewx-aqi#14]
https://github.com/jonathankoren/weewx-aqi/blob/fd1d500def49853b3dc483b6ff7b0e12d2b7774f/bin/user/aqi/units.py#L76

$current($data_binding='aqi_binding').aqi_pm10_0 is displaying 6 decimals - X.XXXXXX

**Comment by Distortionist** [comment]
I don't know if the maintainer is around anymore man. We need someone to take over and make it better! I use this extension too and it needs refining. I don't know how to program!

**Comment by steepleian** [comment]
Distortionist,
Calm down there, all these guys provide their work freely in their spare time. Just imagine if you have to pay for this work by the hour, how much would it cost? Making comments like that is not the best way to get help from anybody. Now if I have your attention you will understand that your issue with 6 decimals. If your read the WeeWX documentation carefully you will find out how to format you tags to whatever number of decimal places you require.

**Comment by Distortionist** [comment]
> Distortionist,
> Calm down there, all these guys provide their work freely in their spare time. Just imagine if you have to pay for this work by the hour, how much would it cost? Making comments like that is not the best way to get help from anybody. Now if I have your attention you will understand that your issue with 6 decimals. If your read the WeeWX documentation carefully you will find out how to format you tags to whatever number of decimal places you require.

I didn't mean no offence or anything, I just don't know if the maintainer is around anymore that is all. He has not responded to anyone in a long time. it is misko903 that opened this issue. I have a separate issue if you are willing to help I can open it. I have not because I really think the maintainer is gone!

**Comment by steepleian** [comment]
He is frequently around but is probably a busy man. I use this extension
myself and issues do get resolved. Sometimes we have to be patient.
