### ISSUE TITLE
AQI is slow to drop after spike

### ISSUE THREAD

**Issue by Distortionist** [jonathankoren/weewx-aqi#15]
If my PM2.5 sensor has a spike for whatever reason, the AQI is slow to respond and spike too, and then it takes forever to return to normal even after normal readings have resumed. Here is a graph of it happening. It is annoying. 

![image](https://user-images.githubusercontent.com/72505233/105354070-6d47b400-5bc6-11eb-9ec8-0a185330cf45.png)

**Comment by jonathankoren** [comment]
Are you using NowCast? 

EPA's AQI is based off a 24 hour average. NowCast was developed for more real time data.

file:///Users/jonathan/Downloads/aqi-technical-assistance-document-sept2018.pdf
