### ISSUE TITLE
Weewx Died This Morning

### ISSUE THREAD

**Issue by Overcon** [jonathankoren/weewx-aqi#31]
I am not sure what is happening, but this morning, it seems Weewx stopped working. I can reboot and it works for a little bit, then stops working. Here is the log excerpt.

This is the log after a reboot.

Sep 30 14:48:14 weewx-pi systemd[1]: Finished Update UTMP about System Runlevel Changes.
Sep 30 14:48:15 weewx-pi cloud-init[1985]: Cloud-init v. 21.2-3-g899bfaa9-0ubuntu2~20.04.1 running 'modules:final' at Thu, 30 Sep 2021 20:48:15 +0000. Up 56.14 seconds.
Sep 30 14:48:15 weewx-pi cloud-init[1985]: Cloud-init v. 21.2-3-g899bfaa9-0ubuntu2~20.04.1 finished at Thu, 30 Sep 2021 20:48:15 +0000. Datasource DataSourceNone.  Up 56.49 seconds
Sep 30 14:48:15 weewx-pi cloud-init[1985]: 2021-09-30 20:48:15,466 - cc_final_message.py[WARNING]: Used fallback datasource
Sep 30 14:48:15 weewx-pi systemd[1]: Finished Execute cloud user/final scripts.
Sep 30 14:48:15 weewx-pi systemd[1]: Reached target Cloud-init target.
Sep 30 14:48:15 weewx-pi systemd[1]: Startup finished in 9.642s (kernel) + 46.957s (userspace) = 56.599s.
Sep 30 14:48:23 weewx-pi weewx[867] DEBUG user.gw1000: Next update in 20 seconds
Sep 30 14:48:23 weewx-pi weewx[867] DEBUG weewx.restx: Wunderground-RF: wait interval (20 < 80) has not passed for record 2021-09-30 14:48:23 MDT (1633034903)
Sep 30 14:48:23 weewx-pi weewx[867] INFO weewx.restx: MQTT: Published record 2021-09-30 14:48:23 MDT (1633034903)
Sep 30 14:48:43 weewx-pi weewx[867] DEBUG user.gw1000: Next update in 20 seconds
Sep 30 14:48:43 weewx-pi weewx[867] DEBUG weewx.restx: Wunderground-RF: wait interval (40 < 80) has not passed for record 2021-09-30 14:48:43 MDT (1633034923)
Sep 30 14:48:43 weewx-pi weewx[867] INFO weewx.restx: MQTT: Published record 2021-09-30 14:48:43 MDT (1633034923)
Sep 30 14:49:03 weewx-pi weewx[867] DEBUG user.gw1000: Next update in 20 seconds
Sep 30 14:49:03 weewx-pi weewx[867] DEBUG weewx.restx: Wunderground-RF: wait interval (60 < 80) has not passed for record 2021-09-30 14:49:03 MDT (1633034943)
Sep 30 14:49:03 weewx-pi weewx[867] INFO weewx.restx: MQTT: Published record 2021-09-30 14:49:03 MDT (1633034943)
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG user.gw1000: Next update in 20 seconds
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG user.aqixtypes: UsEpaAqiXTypes.get_scalar(aqi_pm2_51_24h_avg,,)
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG user.aqixtypes: UsEpaAqiXTypes.get_scalar(aqi_pm2_52_24h_avg,,)
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG user.aqixtypes: UsEpaAqiXTypes.get_scalar 'pm2_52_24h_avg' not in record
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.wxservices: Unknown extensible type 'aqi_pm2_52_24h_avg'
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG user.aqixtypes: UsEpaAqiXTypes.get_scalar(aqi_pm2_51_instant,,)
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG user.aqixtypes: UsEpaAqiXTypes.get_scalar(aqi_pm2_52_instant,,)
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG user.aqixtypes: UsEpaAqiXTypes.get_scalar 'pm2_52' not in record
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.wxservices: Unknown extensible type 'aqi_pm2_52_instant'
Sep 30 14:49:23 weewx-pi weewx[867] INFO weewx.engine: Main loop exiting. Shutting engine down.
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.restx: Shut down WeatherCloud thread.
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.restx: Shut down OWM thread.
Sep 30 14:49:23 weewx-pi weewx[867] INFO weewx.restx: MQTT: Published record 2021-09-30 14:49:23 MDT (1633034963)
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.restx: Shut down MQTT thread.
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.restx: Shut down AWEKAS thread.
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.restx: Shut down WOW thread.
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.restx: Shut down CWOP thread.
Sep 30 14:49:23 weewx-pi weewx[867] DEBUG weewx.restx: Shut down PWSWeather thread.
Sep 30 14:49:24 weewx-pi weewx[867] INFO weewx.restx: Wunderground-RF: Published record 2021-09-30 14:49:23 MDT (1633034963)
Sep 30 14:49:24 weewx-pi weewx[867] DEBUG weewx.restx: Shut down Wunderground-RF thread.
Sep 30 14:49:24 weewx-pi weewx[867] DEBUG weewx.restx: Shut down StationRegistry thread.
Sep 30 14:49:24 weewx-pi weewx[867] INFO user.gw1000: Gw1000Collector thread has been terminated
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__: Caught unrecoverable exception:
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  unsupported operand type(s) for -: 'NoneType' and 'float'
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  Traceback (most recent call last):
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 214, in run
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.CHECK_LOOP, packet=packet))
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      callback(event)
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 624, in check_loop
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      raise BreakLoop
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  weewx.engine.BreakLoop
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  Traceback (most recent call last):
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 640, in post_loop
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      self._catchup(self.engine.console.genArchiveRecords)
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 687, in _catchup
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      for record in generator(lastgood_ts):
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/drivers/__init__.py", line 30, in genArchiveRecords
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      raise NotImplementedError("Method 'genArchiveRecords' not implemented")
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  NotImplementedError: Method 'genArchiveRecords' not implemented
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  Traceback (most recent call last):
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewxd", line 157, in main
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      engine.run()
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 221, in run
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.POST_LOOP))
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      callback(event)
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 642, in post_loop
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      self._software_catchup()
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 705, in _software_catchup
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      self.engine.dispatchEvent(weewx.Event(weewx.NEW_ARCHIVE_RECORD,
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      callback(event)
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/user/aqi/service.py", line 311, in new_archive_record
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      temp_kelvin = weewx.units.CtoK(weewx.units.FtoC(row['outTemp']))
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/units.py", line 44, in FtoC
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****      return (x - 32.0) * 5.0 / 9.0
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Sep 30 14:49:24 weewx-pi weewx[867] CRITICAL __main__:     ****  Exiting.
Sep 30 15:02:21 weewx-pi systemd[1]: Starting Cleanup of Temporary Directories...
Sep 30 15:02:22 weewx-pi systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Sep 30 15:02:22 weewx-pi systemd[1]: Finished Cleanup of Temporary Directories.
^C

**Comment by jonathankoren** [comment]
What version are you using?

**Comment by Overcon** [comment]
I just downloaded the one from GitHub and installed it over the other one (which I had installed in July of this year). But it broke this morning, around 4:53 AM. 

 

Is there a way I can get a version number?

**Comment by jonathankoren** [comment]
It's probably 1.3 if you downloaded it recently.

I just pushed 1.4. Try that.
