### ISSUE TITLE
Two Sensors Support

### ISSUE THREAD

**Issue by MksRasp** [jonathankoren/weewx-aqi#38]
I have outdoor and indoor air quality sensors but weewx-aqi support only one sensor. can we get support for the other sensor

**Comment by jonathankoren** [comment]
WeeWx doesn't really support multiple services of the same type. I can' tell you how to hack to the code for your own setup, but it's a bit of an architectural decision. 

If you want, you can hack it to get it to work. Essentially you need to make two copies of AqiService, `AqiService` and `AqiService2`, make sure `AqiService2` is reading out of configs named `[AqiService2]`.  You could probably just copy and the `AqiService` class out of `service.py` and search and replace `AqiService` to `AqiService2`.  I *think* that would work.

Another solution would be to create separate station for one of the sensors, and then combine them into a report, kind of like https://groups.google.com/g/weewx-user/c/jA94mYTD5ZU?pli=1 .
