### ISSUE TITLE
Error on startup with the updated version

### ISSUE THREAD

**Issue by steepleian** [jonathankoren/weewx-aqi#6]
Hi,
Firstly, thanks for this extension. I am attempting to set it up to use the SDS011 particle sensor in conjunction with the weewx-sds011 driver.

Does this version have backward compatibility or is it purely Python3x? The reason I ask is that it is throwing the following error at startup: -

> sudo tail -f /var/log/syslog
May 10 09:25:29 raspberrypi weewx[15155]:     ****      self.service_obj.append(weeutil.weeutil._get_object(svc)(self, config_dict))
May 10 09:25:29 raspberrypi weewx[15155]:     ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1107, in _get_object
May 10 09:25:29 raspberrypi weewx[15155]:     ****      mod = __import__(module)
May 10 09:25:29 raspberrypi weewx[15155]:     ****    File "/home/weewx/bin/user/aqi/service.py", line 15, in <module>
May 10 09:25:29 raspberrypi weewx[15155]:     ****      from . import calculators
May 10 09:25:29 raspberrypi weewx[15155]:     ****    File "/home/weewx/bin/user/aqi/calculators.py", line 80
May 10 09:25:29 raspberrypi weewx[15155]:     ****      class AqiCalculator(metaclass=ABCMeta):
May 10 09:25:29 raspberrypi weewx[15155]:     ****                                   ^
May 10 09:25:29 raspberrypi weewx[15155]:     ****  SyntaxError: invalid syntax
May 10 09:25:29 raspberrypi weewx[15155]:     ****  Exiting.

**Comment by jonathankoren** [comment]
I ran `2to3` on the code and changed `litre` to `liter` because the spelling changed between WeeWX 3.x and 4.x. So it's Python 3. 

Try this release for python2 support:
https://github.com/jonathankoren/weewx-aqi/releases/tag/v1.1.3

**Comment by steepleian** [comment]
Thanks Jonathan,
I picked up the spieling difference last night and pleased to report that it cleared the error.
A question. I am using the UK DAQI. I notice that the category columns are not populated in the aqi.sdb database. Is this correct? I am still getting a background colour but as the readings are at index 1 at the moment have yet to see if this will change when index increases. Am I correct in thinking the category is linked to colour or is it different for DAQI.
Thanks
Ian

**Comment by steepleian** [comment]
To save confusion I will move the database discussion to a new issue.
